import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "@/components/ui/sonner";
import HomeFooter from "@/components/HomeFooter";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Spicyfy - AI Recipes Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" className="dark" suppressHydrationWarning>
        <body className={`${inter.className} bg-[#09090b] text-white selection:bg-purple-500/30 selection:text-white`}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Toaster richColors />
          <HomeFooter />
        </body>
      </html>
    </ClerkProvider>
  );
}